export const INCREMENT_FOO = 'INCREMENT_FOO';
export type INCREMENT_FOO = typeof INCREMENT_FOO;

export const DECREMENT_FOO = 'DECREMENT_FOO';
export type DECREMENT_FOO = typeof DECREMENT_FOO;

export const SAVE_NEW_TRAIN = 'TRAINS/NEW/SAVE_NEW_TRAIN';
export const SAVE_NEW_TRAIN_DONE = 'TRAINS/NEW/SAVE_NEW_TRAIN_DONE';
